[package]
name = "rj"
version = "0.1.0"
description = "FreeBSD jail manager in Rust"
authors = ["Andrew Wasilczuk <akw@ml1.net>"]
edition = "2018"

exclude = [
    ".gitignore",
    ".rustfmt.toml",
    "Makefile",
]

[dependencies]
anyhow = "1.0"
xz2 = "0.1"
tar = "0.4"
reqwest = "0.9"
config = "0.10.1"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
pretty_assertions = "0.6"
rand = "0.7.3"
