debug = false
jails_dataset = "zroot/jails"
jails_mountpoint = "/jails"

# Releases

[source.freebsd12]
type = "freebsd"
release = "12.0-RELEASE"
mirror = "ftp.uk.freebsd.org"
dists = [ "base", "lib32" ]

[source.basejail]
type = "clone"
path = "zroot/jails/base"

# Provisioners

# [provisioner.puppet]
# kind="puppet"
# path="manifest/"

# [provisioner.base]
# kind="shell"
# path="script.sh"

# Jails

[jail.base]
source = "freebsd12"
# provisioners = [ "base" ]

[jail.example]
source = "basejail"
# provisioners = [ "puppet" ]
