jails_dataset = "zroot/jails"
jails_mountpoint = "/jails"

[jail_conf_defaults]
exec_start = "/bin/sh /etc/rc"
exec_stop = "/bin/sh /etc/rc.shutdown"
exec_clean = true
mount_devfs = true

# Releases

[source.freebsd12]
type = "freebsd"
release = "12.0-RELEASE"
mirror = "ftp.uk.freebsd.org"
dists = [ "base", "lib32" ]

[source.base]
type = "clone"
path = "zroot/jails/base"

# Jails

[jail.base]
order = 10
source = "freebsd12"
# run = false
# provisioners = [ "shell" ]

[jail.test1]
order = 20
source = "base"
# provisioners = [ "puppet" ]

[jail.test2]
order = 20
source = "base"
[jail.test2.conf]
host_hostname = "test2.jail"
allow_set_hostname = 1
allow_raw_sockets = 1
ip4_addr = [ "lo0|10.11.11.2/32", "10.23.23.2/32" ]
allow_mount = true