# Global

jails_dataset = "zroot/jails"
jails_mountpoint = "/jails"
jails_defaults = [
    "exec.start = /bin/sh /etc/rc",
    "exec.stop = /bin/sh /etc/rc.shutdown",
    "exec.clean",
    "mount.devfs",
]

# Releases

[source.freebsd12]
type = "freebsd"
release = "12.0-RELEASE"
mirror = "ftp.uk.freebsd.org"
dists = [ "base", "lib32" ]

[source.base]
type = "clone"
path = "zroot/jails/base"

# Provisioners

# [provisioner.puppet]
# type="puppet"
# path="manifest/"

# [provisioner.shell]
# type="shell"
# path="script.sh"

# Jails

[jail.base]
order = 10
source = "freebsd12"
# run = false
# provisioners = [ "shell" ]

[jail.example]
order = 20
source = "base"
# provisioners = [ "puppet" ]

[jail.test]
order = 20
source = "base"
conf = [
    "host.hostname = test.example.com",
    "allow.set_hostname = 1",
    "allow.raw_sockets = 1",
    "ip4.addr = lo0|10.23.23.1",
]