debug = false
jails_dataset = "zroot/jails"
jails_mountpoint = "/jails"

# Releases

[source.freebsd12]
type = "freebsd"
release = "12.0-RELEASE"
mirror = "ftp.uk.freebsd.org"
dists = [ "base", "lib32" ]

[source.base]
type = "clone"
path = "zroot/jails/base"

# Provisioners

# [provisioner.puppet]
# type="puppet"
# path="manifest/"

# [provisioner.shell]
# type="shell"
# path="script.sh"

# Jails

[jail.base]
order = 10
source = "freebsd12"
# run = false
# provisioners = [ "shell" ]

[jail.example]
order = 20
source = "base"
# provisioners = [ "puppet" ]

[jail.anotherone]
order = 19
source = "base"
